# Be sure to update "bedrocktraction" to your website name.
name: bedrocktraction
recipe: wordpress
env_file:
  - .lando.env
excludes:
  - vendor
  - node_modules
config:
  php: "8.2"
  via: nginx
  database: mariadb
  cache: redis
  xdebug: true
  webroot: web
services:
  ezmode:
    type: phpmyadmin
  node:
    type: node
    build:
      - npm install
  appserver:
    overrides:
      # See: https://github.com/docker/for-linux/issues/264#issuecomment-763555307
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-serverName=appserver}"
        XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"
        XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal discover_client_host=true}"
    build:
      - composer install --working-dir=/app --no-progress --no-interaction --no-progress
  build:
    type: node:18
    ssl: true
    scanner: false
  sendmailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  database:
    type: mariadb
    portforward: true
  cache:
    type: redis
    portforward: true
tooling:
  dev:
    description: install theme dependencies and compile assets when files are changed.
    service: node
    cmd:
      - npm install
      - npm run watch
    # Be sure to update "carbonfields" to your theme name.
    dir: /app/web/app/themes/carbonfields
  redis-cli:
    service: cache
  flush:
    service: appserver
    description: Flush all caches
    cmd:
      - appserver: wp rewrite flush
      - appserver: wp cache flush
      - cache: redis-cli FLUSHDB
    dir: /web
  install-plugins:
    service: appserver
    description: Install all base plugins.
    cmd: >-
      lando composer require wpackagist-plugin/spinupwp wpackagist-plugin/limit-login-attempts-reloaded wpackagist-plugin/wp-ses wpackagist-plugin/simple-history wpackagist-plugin/seo-by-rank-math wpackagist-plugin/advanced-custom-fields wpackagist-plugin/patchstack wpackagist-plugin/amazon-s3-and-cloudfront wpackagist-plugin/easy-property-listings wpackagist-plugin/easy-property-listings-xml-csv-import wpackagist-plugin/import-xml-csv-settings-to-rank-math-seo wpackagist-plugin/akismet wpackagist-plugin/index-wp-mysql-for-speed wpackagist-plugin/admin-site-enhancements
  login-live: #Before using this command, make sure to update the SSH credentials and path!
    service: appserver
    description: generate a login link for the live URL.
    # Update this user@ip_address to match your live server's SSH credentials and path.
    cmd: >-
        ssh traction@123.123.123.123 "cd files/web; wp login as 1"
  login:
    service: appserver
    description: Generate administrator login URL
    cmd: >-
        if ! command wp package path aaemnnosttv/wp-cli-login-command >/dev/null 2>&1; then
          mkdir -p ~/.wp-cli/packages;
          cd ~/.wp-cli/packages;
          composer config repositories.wp-cli --unset 2>/dev/null;
          composer require aaemnnosttv/wp-cli-login-command dev-master;
          cd /app;
        fi;
        wp plugin is-active wp-cli-login-server || wp login install --activate --yes;
        wp login as 1